version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

    # ignore only major updates
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
