version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    # automatically label PRs
    labels:
      - "dependencies"
      - "github-actions"

    # limit number of open PRs
    open-pull-requests-limit: 5
